services:
  db:
    image: postgres
    restart: always
    # set shared memory limit
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "PGPASSWORD=${POSTGRES_PASSWORD}", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - /home/thu4n/db-data:/var/lib/postgresql/data/pgdata

  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
  
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend

  proxy:
    build: ./proxy
    restart: always
    ports: ['80:80']