---
- hosts: all
  become: true

  tasks:
    - name: Clone GitHub repository
      git:
        repo: 'https://github.com/thu4n/devops-practice'
        dest: /home/thu4n/devops-practice

    - name: Run Docker compose
      command: docker compose up -d --build chdir=/home/thu4n/devops-practice