---
- hosts: all
  become: true

  tasks:
    - name: Add the user 'thu4n' and add it to 'sudo'
      user:
        name: thu4n
        group: sudo

    - name: Add SSH key to 'thu4n'
      authorized_key:
        user: thu4n
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
        # The above line got me error when running in WSL-Ubuntu, potential fix so far:
        # https://github.com/ansible/ansible/issues/30754#issuecomment-508997294

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install Docker
      apt:
        pkg: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Add the 'docker' group
      group: name=docker state=present

    - name: Add to 'docker'
      user:
        name: thu4n 
        groups: docker
        append: true